from setuptools import setup

setup(
    name = "pyreactive",
    version = "0.1.5",
    author = "Pratheek Adidela",
    author_email = "apratheek@gmail.com",
    description = "A Reactive Programming module for Python 2 and 3",
    license = "MIT",
    keywords = "Reactive Programming, Observables, Subscriptions, Notify",
    url = "https://github.com/apratheek/PyReactive",
    packages = ['pyreactive'],
    long_description = open("README.rst").read(),
    classifiers = [
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Education",
        "Intended Audience :: Financial and Insurance Industry",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Topic :: Office/Business :: Financial",
        "Topic :: Office/Business :: Financial :: Investment",
        "Topic :: Scientific/Engineering",
        "Topic :: Scientific/Engineering :: Information Analysis",
        "Topic :: Scientific/Engineering :: Mathematics",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
)
